import localFont from 'next/font/local';
import './globals.css';
import Providers from './components/Providers';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'DMShop',
  description: 'Generated by DM',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar space-x-4 p-4">
          <Link href="/">HOME</Link>
          <Link href="/userposts">ADMIN</Link>
          <Link href="/list">LIST</Link>
          <Link href="/cart">CART</Link>
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
